#!/bin/bash

PREFIXRC=".prefixrc"

export WINEPREFIX="$PWD"
export WINEARCH="win64"
export WINEDEBUG="error+dll"
export PREFIXNAME="$(basename $PWD)"

if ! [ -f $PREFIXRC ]; then
	cat << EOF > $PREFIXRC
export PS1='\[\e[1m\][\[\e[96m\]$PREFIXNAME\[\e[0;1m\]]\[\e[0m\] '

if [ -r /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
fi

export WINEARCH=$WINEARCH

echo -e "\e[93m${PREFIXNAME} ($WINEARCH) -- $(wine --version)\e[0m"
echo -e "\e[2;3;95mRun \e[4mexit\e[0;2;3;93m to restore the terminal.\e[0m"
EOF
fi

bash --noprofile --rcfile $PREFIXRC
